// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imesoffnlxamxytfukrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZXNvZmZubHhhbXh5dGZ1a3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTY3OTksImV4cCI6MjA3MzI3Mjc5OX0.xWY7dDxjifwxDBDPlWDNMBTTo1J6WJbFcoaw9LKWlXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});